'use strict';

// Generates src/index.mjs from src/index.cjs as a genuine, standalone ES
// module: a browser's native ESM loader executes `.cjs`-imported files as
// modules too, and has no `require`/`module.exports` interop, so a thin
// `import axios from './index.cjs'` wrapper throws
// "does not provide an export named 'default'" outside of Node/bundlers
// that add CJS interop. index.cjs's body uses no `require()` calls and no
// other CommonJS-only syntax besides the `'use strict'` prologue and the
// trailing `module.exports` line, so stripping those and appending real
// `export` statements produces a working, single-source-of-truth ESM build.

const fs = require('node:fs');
const path = require('node:path');

const cjsPath = path.join(__dirname, '..', 'src', 'index.cjs');
const mjsPath = path.join(__dirname, '..', 'src', 'index.mjs');

// Names already declared as top-level bindings in index.cjs's body (classes,
// functions, consts) - re-exported directly rather than destructured from
// `axios`, since destructuring them too would redeclare the same identifier.
const DIRECT_EXPORTS = [
  'Axios', 'AxiosError', 'AxiosHeaders', 'AxiosURLSearchParams', 'CancelToken', 'CanceledError',
  'HttpStatusCode', 'VERSION', 'mergeConfig', 'toFormData', 'formToJSON', 'getAdapter'
];
// Names that only exist as properties assigned onto the `axios` object
// (inline arrow functions, aliases) - not top-level bindings, so these are
// safe to pull off `axios` directly.
const DESTRUCTURED_EXPORTS = ['Cancel', 'all', 'spread', 'isCancel', 'isAxiosError'];

function generate() {
  const source = fs.readFileSync(cjsPath, 'utf8');
  const withoutDirective = source.replace(/^'use strict';\r?\n\r?\n/, '');
  const moduleExportsPattern = /\r?\nmodule\.exports = axios;\r?\n$/;
  if (!moduleExportsPattern.test(withoutDirective)) {
    throw new Error('src/index.cjs does not end with the expected `module.exports = axios;` line - update scripts/build-esm.cjs');
  }
  const body = withoutDirective.replace(moduleExportsPattern, '');
  const footer = `\nexport { ${DIRECT_EXPORTS.join(', ')} };\nexport const { ${DESTRUCTURED_EXPORTS.join(', ')} } = axios;\nexport default axios;\n`;
  const banner = '// Generated by scripts/build-esm.cjs from index.cjs. Do not edit directly - run `npm run build:esm`.\n\n';
  return banner + body + footer;
}

function main() {
  const generated = generate();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(mjsPath) ? fs.readFileSync(mjsPath, 'utf8') : '';
    if (current !== generated) {
      console.error('src/index.mjs is out of date with src/index.cjs. Run `npm run build:esm`.');
      process.exit(1);
    }
    console.log('src/index.mjs is up to date.');
    return;
  }
  fs.writeFileSync(mjsPath, generated);
  console.log('wrote src/index.mjs');
}

module.exports = { generate };

if (require.main === module) main();
